### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [erskin19/StaticRailsApp#1]
Looks mostly good, except for a few things I'd like you to fix:
- [There's a `<header>` tag](https://github.com/erskin19/StaticRailsApp/blob/master/HelloWorld/app/views/layouts/application.html.erb#L10) that's never closed.
- I see a `static.js` _and_ a `static.js.coffee` file. Can you delete one of them?
- I see some hard-tabs in the CSS files. Can you update them to use two-space soft-tabs instead?
- I don't see a reason to spread the CSS between `application.css` and `static.css`, so can you instead move everything to `static.css`?

**Comment by chrisvfritz** [comment]
I'd also like `config.ru` and other files on that level at the root of the project as well. Can you move everything to the root of the repo, then delete the `HelloWorld` folder? In the future, you can avoid this problem by making sure you only `git init` once _inside_ the folder that `rails new` generates.

**Comment by erskin19** [comment]
They should be fixed now.

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
